console.log(1+1);
console.log(typeof(1+1));
console.log(1+'1');
console.log(typeof(1+'1'));
console.log('a'+'b');
console.log(1+false);
console.log('1'+true);
console.log('1'+false);
console.log(typeof('1'+true));
console.log('1'-1);
console.log(typeof('1'-1));
console.log('1'*2);
console.log(typeof('1'*2));
console.log('1'-true);
console.log(typeof('1'-true));
console.log('1'*true);
console.log(typeof('1'*true));
var num1=3,num2=true,num3='tedu';
var ans1,ans2,ans3;
ans1=num1+num2+num3;
ans2=num2+num3+num1;
ans3=num3+num1+num2;
console.log(ans1,ans2,ans3);